apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  labels:
    app: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
        - name: gitea
          image: gitea/gitea:latest
          ports:
            - containerPort: 3000
            - containerPort: 22
          env:
            - name: USER_UID
              value: "1000"
            - name: USER_GID
              value: "1000"
            - name: GITEA__security__ALLOWED_HOST_LIST
              value: "jenkins"
          volumeMounts:
            - name: gitea-storage
              mountPath: /data
      volumes:
        - name: gitea-storage
          persistentVolumeClaim:
            claimName: gitea-pvc